# Generated by Django 4.2.6 on 2024-02-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(default='GEG 113', max_length=10),
            preserve_default=False,
        ),
    ]
